version: '3.8'

services:   

  be:
    build:
      
      dockerfile: dockerfile
      context: ./be
    ports:
      - '8001:8000'
    stdin_open: true   
    tty: true
    env_file:
      - .env
    volumes:
     - ./be:/app    
  fe:
  
    volumes: 
      - ./fe:/app
      - /app/node_modules
  
    build:
      
      dockerfile: dockerfile
      context: ./fe
    ports:
      - '3001:3000'  
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:8001   

  
      
   
